inventory/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('album/new/', views.album_new, name='album_new'),
    path('artist/new/', views.artist_new, name='artist_new')
]

record_store/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('inventory/', include('inventory.urls')),
    path('admin/', admin.site.urls),
]

inventory/models.py
from django.db import models

class Artist(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Album(models.Model):
    title = models.CharField(max_length=255)
    year = models.IntegerField()
    stock_level = models.IntegerField()
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

inventory/forms.py
from django import forms

from .models import Album, Artist

class AlbumForm(forms.ModelForm):
    artist = forms.ModelChoiceField(Artist.objects.all())
    class Meta:
        model = Album
        fields = ('title', 'year', 'stock_level', 'artist')

class ArtistForm(forms.ModelForm):
    class Meta:
        model = Artist
        fields = ('name',)

inventory/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from inventory.models import *
from .forms import AlbumForm, ArtistForm
from django.contrib.auth.decorators import login_required

def index(request):
    artists = Artist.objects.all()
    return render(request, "inventory/index.html", locals())

def album_new(request):
    if request.method == "POST":
        form = AlbumForm(request.POST) 
        if form.is_valid():
            album = form.save(commit=False)
            album.save()
            return redirect('index')
    else:
        form = AlbumForm()
        return render(request, 'inventory/album_form.html', {'form': form})

def artist_new(request):
    if request.method == "POST":
        form = ArtistForm(request.POST) 
        if form.is_valid():
            artist = form.save(commit=False)
            artist.save()
            return redirect('index')
    else:
        form = ArtistForm()
        return render(request, 'inventory/artist_form.html', {'form': form})

def album_delete(request, id):
    album = Album.objects.get(id)
    if request.method == "Delete":
        album.delete()
        return redirect('index')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	<link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<title>Zoo Records</title>
</head>

<body>
		<nav class="navbar navbar-expand-sm">
		<!-- <nav class="navbar navbar-inverse"> -->
				<div class="container-fluid">
				  <div class="navbar-header">
					<button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#myNavbar" aria-controls="myNavbar" aria-expanded="false" aria-label="Toggle navigation">
					  <span class="navbar-toggler-icon"></span>
					  <!-- <span class="navbar-toggler-icon"></span> -->
					  <!-- <span class="navbar-toggler-icon"></span> -->
					</button>	
				  </div>
				  <div class="collapse navbar-collapse" id="myNavbar">
					<ul class="nav navbar-nav">
							<li class="nav-item"><a class="navbar-link" href="{% url 'index' %}">Home</a></li>
							<li class="nav-item"><a class="navbar-link" href="{% url 'album_new' %}">Add Album</a></li>
							<li class="nav-item"><a class="navbar-link" href="{% url 'artist_new' %}">Add Artist</a></li>
					</ul>
				  </div>

				  <form class="form-inline">
						<input class="form-control" type="search" placeholder="Search" aria-label="Search">
						<button class="btn btn-outline-success" type="submit">Search</button>
					  </form>

				</div>
			  </nav>

	<!--  -->
	<!-- <div class="pos-f-t">
		<div class="collapse" id="navbarToggleExternalContent">
			<div class="bg-dark p-4">
					<ul class="navbar-nav">
							<li class="nav-item"><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
							<li class="nav-item"><a class="navbar-brand" href="{% url 'album_new' %}">Add Album</a></li>
							<li class="nav-item"><a class="navbar-brand" href="{% url 'artist_new' %}">Add Artist</a></li>
						</ul> -->
				<!-- <h4 class="text-white">Collapsed content</h4>
				<span class="text-muted">Toggleable via the navbar brand.</span> -->
			<!-- </div>
		</div> -->

		<!-- <nav class="navbar navbar-dark bg-dark">
			<a class="navbar-brand" href="#">Menu</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse"
				data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false"
				aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse">
				<ul class="navbar-nav">
					<li class="nav-item"><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
					<li class="nav-item"><a class="navbar-brand" href="{% url 'album_new' %}">Add Album</a></li>
					<li class="nav-item"><a class="navbar-brand" href="{% url 'artist_new' %}">Add Artist</a></li>
				</ul>
			</div>
		</nav>
	</div> -->

	<div class="page-header">
		<h1>Zoo Records</h1>

	</div>

	{% block content %}

	{% endblock %}
</body>

</html>

templates/inventory/album_form.html
{% extends 'base.html' %}

{% block content %}
<div class="card">
  <h3>New Album</h3>
  <form method="POST" class="inventory-form">
    {% csrf_token %}
    <div class="form-group">
      {{ form.as_p }}
    </div>
    <button type="submit" class="save btn btn-default">Save</button>
</div>
</class>
{% endblock %}

templates/inventory/artist_form.html
{% extends 'base.html' %}

{% block content %}
<div class='card'>
  <h3>New Artist</h3>
  <form method="POST" class="inventory-form">
    {% csrf_token %}
    <div class="form-group">
      {{ form.as_p }}
    </div>
    <button type="submit" class="save btn btn-default">Save</button>
  </form>
</div>
{% endblock %}

templates/inventory/index.html
{% extends "base.html" %}

{% block content %}

<div class="content-container-fluid">
	<div class="row">
		<div class="col-sm-12-md-6">
			{% for artist in artists %}
			<div class="card"> 
				<div class="inventory-item">
					<div class="card-header">
						<h3>{{ artist.name }}</h3>
					</div>
					{% for album in artist.album_set.all %}
					<div class="card-body">
						<li>{{ album.title }} - {{ album.year }}
							<button type="button" class="btn btn-light"> Delete this Album</button>
						</li>
					</div>
					{% endfor %}
				</div>
			</div>
			{% endfor %}

		</div>
	</div>
</div>
{% endblock %}